### ISSUE TITLE
Failing Unit Tests in TestMirrorOutput and TestSolarFieldOutput

### ISSUE THREAD

**Issue by braden6521** [sandialabs/OpenCSP#109]
The following unit tests fail on Windows2022. These errors are not reproducible locally. 

- TestMirrorOutput::test_heliostat_05W01_and_14W01
- TestMirrorOutput::test_solar_field
- TestRayTraceOutput::test_changing_time_of_day
- TestSolarFieldOutput::test_multi_heliostat
- TestSolarFieldOutput::test_solar_field_subset

**Comment by braden6521** [comment]
@bbean23, @e10harvey: I cannot figure out why these failures are occurring. You can see these failures hanging up the following PRs: 
- https://github.com/sandialabs/OpenCSP/pull/106
- https://github.com/sandialabs/OpenCSP/pull/107
- https://github.com/sandialabs/OpenCSP/pull/108

**Comment by e10harvey** [comment]
Triage notes:
- This happens with both python3.10 and python3.11
- ubi8 is using and passing with matplotlib version 3.8.4
- windows2022 is using matplotlib version 3.9.0 (matplotlib-inline-0.1.7)
- These tests last passed in windows2022 with matplotlib version 3.8.4 (matplotlib-inline-0.1.7)

**Comment by e10harvey** [comment]
> @e10harvey, no these happen very regularly. These specific five unit test every time.

Ok, thank you. https://github.com/e10harvey/OpenCSP/commit/34c94df9ad328a44393d3c7894d3b8fc77084672 resolves this issue.

**Comment by e10harvey** [comment]
Closing as completed.
