### ISSUE TITLE
make the tests work

### ISSUE THREAD

**Issue by bbean23** [sandialabs/OpenCSP#15]
Depends on #12

**Comment by e10harvey** [comment]
@bbean23: Please see the test_camera_calibration failures from #28 (https://github.com/sandialabs/OpenCSP/actions/runs/8330630942/job/22795731767?pr=28).

**Comment by e10harvey** [comment]
> @bbean23: Please see the test_camera_calibration failures from #28 (https://github.com/sandialabs/OpenCSP/actions/runs/8330630942/job/22795731767?pr=28).

These were fixed via #42 : )
